electric_power <- read.table("./household_power_consumption.txt", sep = ";", na.strings = c("?",""), header = TRUE)
data <- subset(electric_power, electric_power$Date == "1/2/2007" | electric_power$Date == "2/2/2007")
data$DateTime <- as.POSIXct(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
Sys.setlocale("LC_TIME", "English")
par(mar = c(4, 4, 2, 1), oma = c(1, 1, 3, 1))
plot(data$DateTime, data$Sub_metering_1, type="n", cex.lab=0.75, cex.axis = 0.75, main = "", xlab ="", ylab = "Energy sub metering")
lines(data$DateTime,data$Sub_metering_1)
lines(data$DateTime,data$Sub_metering_2, col = "red")
lines(data$DateTime,data$Sub_metering_3, col = "blue")
legend("topright", cex=0.75, pch = "", y.intersp=0.75, x.intersp=0.25, lwd = 1, col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file = "plot3.png",width = 480, height = 480)
dev.off()