electric_power <- read.table("./household_power_consumption.txt", sep = ";", na.strings = c("?",""), header = TRUE)
data <- subset(electric_power, electric_power$Date == "1/2/2007" | electric_power$Date == "2/2/2007")
data$DateTime <- as.POSIXct(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
hist(data$Global_active_power, cex.lab=0.75, cex.axis = 0.75, col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.copy(png, file = "plot1.png",width = 480, height = 480)
dev.off()